name: Tahoe Beta 1 Recovery Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download macOS Installer
        run: |
          #curl -L -o /tmp/InstallAssistant.pkg https://swcdn.apple.com/content/downloads/26/20/082-55599-A_UZPH7KLA4Q/fddo2aezqd7xchfjwh4244kwixjsut4boc/InstallAssistant.pkg
          curl -L -o /tmp/InstallAssistant.pkg https://swcdn.apple.com/content/downloads/47/16/089-70987-A_PWKNKEFQ1D/sjlq45liw0g5lor3a6i89vz7paml1xpq6w/InstallAssistant.pkg

      - name: Install the assistant
        run: |
          sudo installer -pkg /tmp/InstallAssistant.pkg -target /

      - name: Generate macOS Installer
        run: |
          sudo hdiutil create -o /tmp/Sequoia -size 20000m -volname 'Sequoia' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/Sequoia.dmg -noverify -mountpoint /Volumes/Sequoia
          sleep 10
          sudo /Applications/'Install macOS Beta'.app/Contents/Resources/createinstallmedia --volume /Volumes/Sequoia --nointeraction
          cp -R '/Volumes/Install macOS Beta/BaseSystem' /tmp/BaseSystem

      - name: Upload com.apple.recovery.boot
        uses: actions/upload-artifact@v4
        with:
          name: com.apple.recovery.boot
          path: /tmp/BaseSystem/*
          compression-level: 9
